{% set name = "pysyncrosim" %}
{% set version = "1.0.28" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pysyncrosim-{{ version }}.tar.gz
  sha256: 19da3de253e8a32f2d25b10d8c2a346251a4742b3cff210bd72f1f02be5fd440

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - pandas 
    - numpy
    - rasterio
  run:
    - python >=3.8
    - pandas
    - numpy
    - rasterio

test:
  imports:
    - pysyncrosim
    - tests
  commands:
    - pip check
  requires:
    - pip
    - pytest

about:
  home: https://syncrosim.com/
  summary: Python interface to SyncroSim
  license: MIT
  license_file: LICENSE
  doc_url: https://pysyncrosim.readthedocs.io/en/latest/
  dev_url: https://github.com/syncrosim/pysyncrosim/

extra:
  recipe-maintainers:
    - katieb1
